1. Basic Matrix Operations
==

Like vectors, matrices have their own set of algebraic operations. In this mission, we'll learn the core matrix operations and build up to using some of them to solve the matrix equation. Let's first start with matrix addition and subtraction.

If you recall from the previous mission, a matrix consists of one or more column vectors.

<img width="400" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1tHzgogOe0_b6moTRIsWXHyHAu1ExrBB1">

Because of that, the operations from vectors also carry over to matrices. We could perform vector addition and subtraction between vectors with the same number of rows. We can perform matrix addition and subtraction between matrices containing the same number of rows and columns.

<img width="500" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=16B5-SJwHqQuYRLOHXtgpfuPGdrECoB0F">

As with vectors, matrix addition and subtraction works by distributing the operations across the specific elements and combining them.

<img width="500" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1S64jW7NWmgQJe32A1DU9zKoy_2SAo3N4">

Lastly, we can also multiply a matrix by a scalar value, just like we can with a vector.

<img width="400" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1BJXsqp4BSnl-dzE4Z2oU8iRNzBofttcw">

Let's practice applying these operators using NumPy.




2. Matrix Vector Multiplication
==

The matrix equation we discussed briefly in the last mission is an example of **matrix-vector multiplication**. When we multiply a matrix by a vector, we are essentially combining each row in the matrix with the column vector.


<img width="600" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1-fF8lBDbgY4QJAj3HzvU7OoseLhU1av-">

To multiply a matrix by a vector, the number of columns in the matrix needs to match the number of rows in the vector.


<img width="600" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1pgMQpBJ2jbd7XJssACdfloQ6vO00AuSD">


To multiply a matrix with a vector in NumPy, we need to use the [numpy.dot() function](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html).

In [3]:
import numpy as np
matrix_a = np.asarray([
    [0.7, 3, 9],
    [1.7, 2, 9],
    [0.7, 9, 2]
], dtype=np.float32)

vector_b = np.asarray([
    [1], 
    [2], 
    [1]
], dtype=np.float32)

ab_product = np.dot(matrix_a, vector_b)
ab_product

array([[ 15.69999981],
       [ 14.69999981],
       [ 20.70000076]], dtype=float32)

3. Matrix Multiplication
==

Because a matrix consists of column vectors, we can extend what we learned about matrix vector multiplication to multiply matrices together. In matrix vector multiplication, we performed a dot product between each row in the matrix and the column vector. In matrix multiplication, we extend this to perform a dot product between each row in the first matrix and each row in the second matrix.

<img width="600" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1AZbqsaNVG-tzEED_zKi5qokm2D9Q-MSw">

As with matrix vector multiplication, the columns in the first matrix need to match the number of rows in the second matrix.

<img width="200" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1o8LScOD7H42tcOSowTN4lTBmhf_oUn0g">

Note that the order of multiplication also matters.

<img width="500" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1xRJ-2OohcNPBzaXLaKyORZHA7WycwGIq">

To multiply vectors in NumPy, we use the same **numpy.dot()** function we used in the last screen.

In [6]:
matrix_a = np.asarray([
    [0.7, 3],
    [1.7, 2],
    [0.7, 9]
], dtype=np.float32)

matrix_b = np.asarray([
    [113, 3, 10],
    [1, 0, 1],
], dtype=np.float32)
product_ab = np.dot(matrix_a, matrix_b)
product_ba = np.dot(matrix_b, matrix_a)

In [7]:
product_ab

array([[  82.09999847,    2.0999999 ,   10.        ],
       [ 194.1000061 ,    5.10000038,   19.        ],
       [  88.09999847,    2.0999999 ,   16.        ]], dtype=float32)

In [9]:
product_ba

array([[  91.19999695,  435.        ],
       [   1.39999998,   12.        ]], dtype=float32)

4. Matrix Transpose
==

The transpose of a matrix switches the rows and columns of a matrix. You can think of the transpose operation as a rotation. In data science, we're often working with data tables of different dimensions. Because of the requirements for matrix multiplication, we sometimes want to take the transpose of a matrix to allow us to multiply matrices together that, by default, don't overlap in number of rows and columns.

Here's what the transpose of a matrix looks like visually:

<img width="200" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1YmjOgn1n4agwpQQVVheQJpJeXOqGqCtt">


Mathematically, we use the notation AT to specify the transpose operation.

$$A^T+B^T=C$$

The transpose has a few different interesting rules that are a bit intuitive. For example, when taking the transpose of the sum of two matrices, we can distribute the transpose operation to each matrix:

$$(A+B)^T=A^T+B^T$$

One counterintuitive rule is when we take the transpose of the product of 2 matrices:

$$(AB)^T=B^TA^T$$

Let's explore these properties using NumPy. To compute the transpose of a NumPy ndarray, we need to use the [numpy.transpose()](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.transpose.html) function.


In [12]:
matrix_a = np.asarray([
    [0.7, 3],
    [1.7, 2],
    [0.7, 9]
], dtype=np.float32)

matrix_b = np.asarray([
    [113, 3, 10],
    [1, 0, 1],
], dtype=np.float32)

transpose_a = np.transpose(matrix_a)
print(np.transpose(transpose_a))

trans_ba = np.dot(np.transpose(matrix_b), np.transpose(matrix_a))
print(trans_ba)

trans_ab = np.dot(np.transpose(matrix_a), np.transpose(matrix_b))
print(trans_ab)

product_ab = np.dot(matrix_a, matrix_b)
print(np.transpose(product_ab))

[[ 0.69999999  3.        ]
 [ 1.70000005  2.        ]
 [ 0.69999999  9.        ]]
[[  82.09999847  194.1000061    88.09999847]
 [   2.0999999     5.10000038    2.0999999 ]
 [  10.           19.           16.        ]]
[[  91.19999695    1.39999998]
 [ 435.           12.        ]]
[[  82.09999847  194.1000061    88.09999847]
 [   2.0999999     5.10000038    2.0999999 ]
 [  10.           19.           16.        ]]


5. Indentity Matrix
==

In the matrix equation that we discussed in the last mission, we're trying to solve for the vector $\overrightarrow{x}$.

$$A\overrightarrow{x}=\overrightarrow{b}$$


Right now, the matrix $A$ multiplies the vector $\overrightarrow{x}$ and we need a way to cancel $A$.

Let's look at the identity matrix, which we touched on briefly at the end of the first mission in this course. If you recall, the identity matrix contains 1 along the diagonals and 0 elsewhere. Here's what the $2x2$ identity matrix looks like, often represented symbolically using $I_2$:

$$I_2=\begin{bmatrix}1 & 0 \\0 & 1\end{bmatrix}$$

When we multiply $$I_2$$ with any vector containing 2 elements, the resulting vector matches the original vector exactly:

$$I_2\overrightarrow{x}=\overrightarrow{x}$$

This is because each element in the vector is multiplied exactly once by the diagonal 1 value in the identity matrix:

<img width="400" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1Sh25NEL_FDxPKsewMUOXwOEU29bwoVHq">



**If we can transform matrix $A$ and convert it into the identity matrix, then only the solution vector will remain $\overrightarrow{x}$**. Let's practice working with the identity matrix before exploring how to transform $A$ into $I$.

We can create any $I_n$ identity matrix using the [numpy.identity()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.identity.html) function. This function only has 1 required parameter, n, which specifies the n x n identity matrix we want.

In [14]:
i_2 = np.identity(2)
i_3 = np.identity(3)

matrix_33 = np.asarray([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix_23 = np.asarray([
    [0.7, 3, 1],
    [1.7, 2, 10],
], dtype=np.float64)

identity_33 = np.dot(i_3, matrix_33)
identity_23 = np.dot(i_2, matrix_23)

print(identity_33)
print(identity_23)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[  0.7   3.    1. ]
 [  1.7   2.   10. ]]


6. Matrix Inverse
==

Now that we're more familiar with the identity matrix, let's discuss how to cancel the coefficient matrix $A$. Said another way, we want to transform $A$ into the identity matrix $I$. Multiplying the **inverse** of a matrix by the matrix accomplishes this task.

The matrix inverse is similar to the idea of the multiplicative inverse. For example, let's say we want to solve for x in the equation $5x=10$. To do so, we need to multiply both sides by the multiplicative inverse of $5$, which is $5^{−1}$ (or $1/5$):

$$5^{−1}\times 5x=5^{−1}\times10$$


The inverse of 5 transforms it to 1 and leaves us with the solution: $x=2$. To solve for the vector $\overrightarrow{x}$ in the matrix equation, we need to multiply both sides by the inverse of $A$:

$$A^{−1}A\overrightarrow{x}=A^{−1}\overrightarrow{b}$$


This simplifies to $I\overrightarrow{x}=A^{−1}\overrightarrow{b}$ and we're then left with the formula for calculating the solution vector:

$$\overrightarrow{x}=A^{−1}\overrightarrow{b}$$

While we use the matrix inverse to cancel out specific terms in the same fashion as the multiplicative inverse, the calculation is completely different. Let's understand the calculation for the inverse of a $2x2 matrix$.



If $A=\begin{bmatrix}a & b \\c & d\end{bmatrix}$ then $A^{−1}=\frac{1}{ad−bc}\begin{bmatrix}d & -b \\-c & a\end{bmatrix}$.

The term $ad−bc$ is known as the **determinant** and is often written as $det(A)=ad−bc$ or as $|A|=ad−bc$. Because we're dividing by the determinant when calculating the matrix inverse, **a 2 x 2 matrix is only invertible if the determinant is not equal to 0**. In this step and the next step, we'll focus on finding the matrix inverse when A is a 2 x 2 matrix. Later in this mission, we'll walkthrough how to compute the matrix inverse for a higher dimensional matrix (3 x 3 and greater).

Let's implement the matrix inverse in Python before moving on to solving the matrix equation.



In [15]:
matrix_a = np.asarray([
    [1.5, 3],
    [1, 4]
])
def matrix_inverse_two(mat):
    det = (mat[0,0]*mat[1,1] - mat[0,1]*mat[1,0])
    if det == 0:
        raise ValueError("The matrix isn't invertible")
    right_mat = np.asarray([
        [mat[1,1], -mat[0,1]],
        [-mat[1,0], mat[0,0]]
    ])
    inv_mat = np.dot(1/det, right_mat)
    return inv_mat
inverse_a = matrix_inverse_two(matrix_a)
i_2 = np.dot(inverse_a, matrix_a)
print(i_2)

[[ 1.  0.]
 [ 0.  1.]]


7. Solving The Matrix Equation
==

Now that we know how to compute the matrix inverse, we can solve our system using the matrix equation $A\overrightarrow{x}=\overrightarrow{b}$:

$$
\begin{bmatrix}30 & -1 \\50 & -1\end{bmatrix}
\begin{bmatrix}x_1\\x_2\end{bmatrix} = 
\begin{bmatrix}-1000\\-100\end{bmatrix}
$$

We start by left multiplying $A^{−1}$ on both sides:

$$
\begin{bmatrix}30 & -1 \\50 & -1\end{bmatrix}^{-1}
\begin{bmatrix}30 & -1 \\50 & -1\end{bmatrix}
\begin{bmatrix}x_1\\x_2\end{bmatrix} = 
\begin{bmatrix}30 & -1 \\50 & -1\end{bmatrix}^{-1}
\begin{bmatrix}-1000\\-100\end{bmatrix}
$$

This simplifies to:


$$
\begin{bmatrix}x_1\\x_2\end{bmatrix} = 
\begin{bmatrix}30 & -1 \\50 & -1\end{bmatrix}^{-1}
\begin{bmatrix}-1000\\-100\end{bmatrix}
$$

Let's finish this last step in Python. To compute the inverse of a NumPy ndarray, we need to use the [numpy.linalg.inv()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html) function.

In [16]:
matrix_a = np.asarray([
    [30, -1],
    [50, -1]
])

vector_b = np.asarray([
    [-1000],
    [-100]
])
matrix_a_inverse = np.linalg.inv(matrix_a)
solution_x = np.dot(matrix_a_inverse, vector_b)
print(solution_x)

[[   45.]
 [ 2350.]]


8. Determinant For Higher Dimensions
==

Before we discuss how to compute the matrix inverse for higher dimensional matrices, let's dive deeper into the determinant and introduce some more terminology. So far, we've mostly worked with matrices that contain the same number orws and columns. These matrices are known as **square matrices** and we can only compute the determinant and matrix inverse for square matrices. In addition, we can only compute the matrix inverse of a square matrix when the determinant is not equal to $0$.

To find the determinant of a higher dimensional square matrix, we need use the more general form of the determinant. Here's what that looks like:

<img width="500" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=16_D5eM_nPzIfMjfy6W_o4TTCBEOBBTDT">

The determinant of a higher-dimensional system involves breaking down the full matrix into **minor matrices**. First, we select a row or column (most teaching materials select the first row). For the first value in that row, we "hide" the other values in that row (2nd and 3rd value in the row) and in that column (2nd and 3rd value in the column), select the rest of the elements as the minor matrix, and multiply the scalar value with the determinant of the minor matrix. We repeat this for the remaining values in the first row. This diagram helps illustrate this much clearer:

<img width="500" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1lnBrAqhjhjB82VfKlYQ_gf-EqzAondyq">

Here's a concrete example:

<img width="500" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1oRQXahRE8N60kPi_TU9i1A3m7-6vwtBV">


To compute the determinant in NumPy, we use the **numpy.linalg.det()** function. We'll leave it to you to read the [documentation](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.linalg.det.html) and learn how to use this function.




In [18]:
matrix_22 = np.asarray([
    [8, 4],
    [4, 2]
])

matrix_33 = np.asarray([
    [1, 1, 1],
    [1, 1, 6],
    [7, 8, 9]
])
det_22 = np.linalg.det(matrix_22)
det_33 = np.linalg.det(matrix_33)

print(det_22)
print(det_33)

0.0
-5.0


9. Matrix Inverse For Higher Dimensions
==

To calculate the matrix inverse for a 3 by 3, or larger, matrix, we need to also work with the more general form of the matrix inverse equation. Similar to the determinant for higher-dimensional matrices, the matrix inverse works by generating minor matrices that are dependent on the position in the matrix. Here's a diagram describing the matrix inverse for a 3 by 3 matrix:


<img width="600" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=1DBsSuIYWntqwn8rd-sBqDJCWRbnwccVz">

While it's helpful to know how to compute the inverse this way for higher dimensional matrices, the amount of careful arithmetic you have to by hand is large. Thankfully, the **numpy.linalg.inv()** function can work with any **n-dimensional** square matrix.

10. Next steps
==

In this mission, we learned about the different matrix operations and how to solve a linear system that's represented using the matrix equation using the matrix inverse. In the next mission, we'll learn the different ways a solution set can be represented and how to calculate the determinant of a higher dimensional matrix.